services:
  whisper-asr-server:
    build:
      context: .
      args:
        BASE_IMAGE: nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04
    gpus: all
    environment:
      WHISPER_DEVICE: cuda
      WHISPER_COMPUTE_TYPE: float16
