-- Tệp này được sử dụng để khởi tạo dữ liệu của nhà cung cấp mô hình. Nó không cần phải được thực hiện bằng tay. Nó sẽ được thực thi tự động khi dự án bắt đầu.
-- --------------------------------------------------------
-- Khởi tạo dữ liệu nhà cung cấp mô hình
DELETE FROM `ai_model_provider`;
INSERT INTO `ai_model_provider` (`id`, `model_type`, `provider_code`, `name`, `fields`, `sort`, `creator`, `create_date`, `updater`, `update_date`) VALUES
-- Nhà cung cấp mô hình VAD
('SYSTEM_VAD_SileroVAD', 'VAD', 'silero', 'SileroVADPhát hiện hoạt động giọng nói', '[{"key":"threshold","label":"Ngưỡng phát hiện","type":"number"},{"key":"model_dir","label":"Danh mục mẫu","type":"string"},{"key":"min_silence_duration_ms","label":"Khoảng thời gian im lặng tối thiểu","type":"number"}]', 1, 1, NOW(), 1, NOW()),

-- Nhà cung cấp mô hình ASR
('SYSTEM_ASR_FunASR', 'ASR', 'fun_local', 'FunASRnhận dạng giọng nói', '[{"key":"model_dir","label":"Danh mục mẫu","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_ASR_SherpaASR', 'ASR', 'sherpa_onnx_local', 'SherpaASRnhận dạng giọng nói', '[{"key":"model_dir","label":"Danh mục mẫu","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_ASR_DoubaoASR', 'ASR', 'doubao', 'Nhận dạng giọng nói động cơ núi lửa', '[{"key":"appid","label":"ứng dụngID","type":"string"},{"key":"access_token","label":"mã thông báo truy cập","type":"string"},{"key":"cluster","label":"cụm","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 3, 1, NOW(), 1, NOW()),

-- Nhà cung cấp mô hình LLM
('SYSTEM_LLM_openai', 'LLM', 'openai', 'OpenAIgiao diện', '[{"key":"base_url","label":"Khái niệm cơ bảnURL","type":"string"},{"key":"model_name","label":"Tên mẫu","type":"string"},{"key":"api_key","label":"APIchìa khóa","type":"string"},{"key":"temperature","label":"nhiệt độ","type":"number"},{"key":"max_tokens","label":"Số lượng token tối đa","type":"number"},{"key":"top_p","label":"top_pgiá trị","type":"number"},{"key":"top_k","label":"top_kgiá trị","type":"number"},{"key":"frequency_penalty","label":"hình phạt tần số","type":"number"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_AliBL', 'LLM', 'AliBL', 'Giao diện Alibaba Bailian', '[{"key":"base_url","label":"Khái niệm cơ bảnURL","type":"string"},{"key":"app_id","label":"ứng dụngID","type":"string"},{"key":"api_key","label":"APIchìa khóa","type":"string"},{"key":"is_no_prompt","label":"Có nên sử dụng địa phương khôngprompt","type":"boolean"},{"key":"ali_memory_id","label":"ký ứcID","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_ollama', 'LLM', 'ollama', 'Ollamagiao diện', '[{"key":"model_name","label":"Tên mẫu","type":"string"},{"key":"base_url","label":"Địa chỉ dịch vụ","type":"string"}]', 3, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_dify', 'LLM', 'dify', 'Difygiao diện', '[{"key":"base_url","label":"Khái niệm cơ bảnURL","type":"string"},{"key":"api_key","label":"APIchìa khóa","type":"string"},{"key":"mode","label":"Chế độ hội thoại","type":"string"}]', 4, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_gemini', 'LLM', 'gemini', 'Geminigiao diện', '[{"key":"api_key","label":"APIchìa khóa","type":"string"},{"key":"model_name","label":"Tên mẫu","type":"string"},{"key":"http_proxy","label":"HTTPđại lý","type":"string"},{"key":"https_proxy","label":"HTTPSđại lý","type":"string"}]', 5, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_coze', 'LLM', 'coze', 'Cozegiao diện', '[{"key":"bot_id","label":"người máyID","type":"string"},{"key":"user_id","label":"người dùngID","type":"string"},{"key":"personal_access_token","label":"mã thông báo truy cập cá nhân","type":"string"}]', 6, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_fastgpt', 'LLM', 'fastgpt', 'FastGPTgiao diện', '[{"key":"base_url","label":"Khái niệm cơ bảnURL","type":"string"},{"key":"api_key","label":"APIchìa khóa","type":"string"},{"key":"variables","label":"biến","type":"dict","dict_name":"variables"}]', 7, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_xinference', 'LLM', 'xinference', 'Xinferencegiao diện', '[{"key":"model_name","label":"Tên mẫu","type":"string"},{"key":"base_url","label":"Địa chỉ dịch vụ","type":"string"}]', 8, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_doubao', 'LLM', 'doubao', 'động cơ núi lửaLLM', '[{"key":"base_url","label":"Khái niệm cơ bảnURL","type":"string"},{"key":"model_name","label":"Tên mẫu","type":"string"},{"key":"api_key","label":"APIchìa khóa","type":"string"}]', 9, 1, NOW(), 1, NOW()),
('SYSTEM_LLM_chatglm', 'LLM', 'chatglm', 'ChatGLMgiao diện', '[{"key":"model_name","label":"Tên mẫu","type":"string"},{"key":"url","label":"Địa chỉ dịch vụ","type":"string"},{"key":"api_key","label":"APIchìa khóa","type":"string"}]', 10, 1, NOW(), 1, NOW()),

-- Nhà cung cấp mô hình TTS
('SYSTEM_TTS_edge', 'TTS', 'edge', 'Edge TTS', '[{"key":"voice","label":"âm sắc","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_doubao', 'TTS', 'doubao', 'động cơ núi lửaTTS', '[{"key":"api_url","label":"APIđịa chỉ","type":"string"},{"key":"voice","label":"âm sắc","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"authorization","label":"Ủy quyền","type":"string"},{"key":"appid","label":"ứng dụngID","type":"string"},{"key":"access_token","label":"mã thông báo truy cập","type":"string"},{"key":"cluster","label":"cụm","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_siliconflow', 'TTS', 'siliconflow', 'dòng chảy dựa trên siliconTTS', '[{"key":"model","label":"người mẫu","type":"string"},{"key":"voice","label":"âm sắc","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"access_token","label":"mã thông báo truy cập","type":"string"},{"key":"response_format","label":"định dạng phản hồi","type":"string"}]', 3, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_cozecn', 'TTS', 'cozecn', 'COZECN TTS', '[{"key":"voice","label":"âm sắc","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"access_token","label":"mã thông báo truy cập","type":"string"},{"key":"response_format","label":"định dạng phản hồi","type":"string"}]', 4, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_fishspeech', 'TTS', 'fishspeech', 'FishSpeech TTS', '[{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"response_format","label":"định dạng phản hồi","type":"string"},{"key":"reference_id","label":"Tài liệu tham khảoID","type":"string"},{"key":"reference_audio","label":"Âm thanh tham khảo","type":"dict","dict_name":"reference_audio"},{"key":"reference_text","label":"Văn bản tham khảo","type":"dict","dict_name":"reference_text"},{"key":"normalize","label":"Nó có được tiêu chuẩn hóa không?","type":"boolean"},{"key":"max_new_tokens","label":"Số lượng token mới tối đa","type":"number"},{"key":"chunk_length","label":"chiều dài khối","type":"number"},{"key":"top_p","label":"top_pgiá trị","type":"number"},{"key":"repetition_penalty","label":"Lặp lại hình phạt","type":"number"},{"key":"temperature","label":"nhiệt độ","type":"number"},{"key":"streaming","label":"Có phát trực tuyến không","type":"boolean"},{"key":"use_memory_cache","label":"Có nên sử dụng bộ nhớ đệm hay không","type":"string"},{"key":"seed","label":"hạt giống","type":"number"},{"key":"channels","label":"Số lượng kênh","type":"number"},{"key":"rate","label":"Tốc độ lấy mẫu","type":"number"},{"key":"api_key","label":"APIchìa khóa","type":"string"},{"key":"api_url","label":"APIđịa chỉ","type":"string"}]', 5, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gpt_sovits_v2', 'TTS', 'gpt_sovits_v2', 'GPT-SoVITS V2', '[{"key":"url","label":"Địa chỉ dịch vụ","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"text_lang","label":"ngôn ngữ văn bản","type":"string"},{"key":"ref_audio_path","label":"Đường dẫn âm thanh tham chiếu","type":"string"},{"key":"prompt_text","label":"Văn bản nhắc nhở","type":"string"},{"key":"prompt_lang","label":"Ngôn ngữ nhắc nhở","type":"string"},{"key":"top_k","label":"top_kgiá trị","type":"number"},{"key":"top_p","label":"top_pgiá trị","type":"number"},{"key":"temperature","label":"nhiệt độ","type":"number"},{"key":"text_split_method","label":"phương pháp phân đoạn văn bản","type":"string"},{"key":"batch_size","label":"kích thước lô","type":"number"},{"key":"batch_threshold","label":"Ngưỡng hàng loạt","type":"number"},{"key":"split_bucket","label":"Có nên xô không","type":"boolean"},{"key":"return_fragment","label":"Có trả lại các mảnh vỡ hay không","type":"boolean"},{"key":"speed_factor","label":"yếu tố tốc độ","type":"number"},{"key":"streaming_mode","label":"Có phát trực tiếp chế độ không","type":"boolean"},{"key":"seed","label":"hạt giống","type":"number"},{"key":"parallel_infer","label":"Có nên lý luận song song không","type":"boolean"},{"key":"repetition_penalty","label":"Lặp lại hình phạt","type":"number"},{"key":"aux_ref_audio_paths","label":"Đường dẫn âm thanh tham chiếu phụ trợ","type":"dict","dict_name":"aux_ref_audio_paths"}]', 6, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gpt_sovits_v3', 'TTS', 'gpt_sovits_v3', 'GPT-SoVITS V3', '[{"key":"url","label":"Địa chỉ dịch vụ","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"text_language","label":"ngôn ngữ văn bản","type":"string"},{"key":"refer_wav_path","label":"Đường dẫn âm thanh tham chiếu","type":"string"},{"key":"prompt_language","label":"Ngôn ngữ nhắc nhở","type":"string"},{"key":"prompt_text","label":"Văn bản nhắc nhở","type":"string"},{"key":"top_k","label":"top_kgiá trị","type":"number"},{"key":"top_p","label":"top_pgiá trị","type":"number"},{"key":"temperature","label":"nhiệt độ","type":"number"},{"key":"cut_punc","label":"Tách dấu câu","type":"string"},{"key":"speed","label":"tốc độ","type":"number"},{"key":"inp_refs","label":"Nhập tài liệu tham khảo","type":"dict","dict_name":"inp_refs"},{"key":"sample_steps","label":"Số bước lấy mẫu","type":"number"},{"key":"if_sr","label":"Có nên sử dụng khôngSR","type":"boolean"}]', 7, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_minimax', 'TTS', 'minimax', 'Minimax TTS', '[{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"group_id","label":"nhómID","type":"string"},{"key":"api_key","label":"APIchìa khóa","type":"string"},{"key":"model","label":"người mẫu","type":"string"},{"key":"voice_id","label":"âm sắcID","type":"string"}]', 8, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_aliyun', 'TTS', 'aliyun', 'Đám mây của AlibabaTTS', '[{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"appkey","label":"phím ứng dụng","type":"string"},{"key":"token","label":"mã thông báo truy cập","type":"string"},{"key":"voice","label":"âm sắc","type":"string"},{"key":"access_key_id","label":"phím truy cậpID","type":"string"},{"key":"access_key_secret","label":"mật khẩu khóa truy cập","type":"string"}]', 9, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_ttson', 'TTS', 'ttson', 'ACGNTTS', '[{"key":"token","label":"mã thông báo truy cập","type":"string"},{"key":"voice_id","label":"âm sắcID","type":"string"},{"key":"speed_factor","label":"yếu tố tốc độ","type":"number"},{"key":"pitch_factor","label":"yếu tố cao độ","type":"number"},{"key":"volume_change_dB","label":"thay đổi âm lượng","type":"number"},{"key":"to_lang","label":"ngôn ngữ mục tiêu","type":"string"},{"key":"url","label":"Địa chỉ dịch vụ","type":"string"},{"key":"format","label":"định dạng","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"emotion","label":"cảm xúc","type":"number"}]', 10, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_openai', 'TTS', 'openai', 'OpenAI TTS', '[{"key":"api_key","label":"APIchìa khóa","type":"string"},{"key":"api_url","label":"APIđịa chỉ","type":"string"},{"key":"model","label":"người mẫu","type":"string"},{"key":"voice","label":"âm sắc","type":"string"},{"key":"speed","label":"tốc độ","type":"number"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 11, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_custom', 'TTS', 'custom', 'Tùy chỉnhTTS', '[{"key":"url","label":"Địa chỉ dịch vụ","type":"string"},{"key":"params","label":"Thông số yêu cầu","type":"dict","dict_name":"params"},{"key":"headers","label":"Tiêu đề yêu cầu","type":"dict","dict_name":"headers"},{"key":"format","label":"định dạng âm thanh","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"}]', 12, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_302ai', 'TTS', '302ai', '302AI TTS', '[{"key":"api_url","label":"APIđịa chỉ","type":"string"},{"key":"authorization","label":"Ủy quyền","type":"string"},{"key":"voice","label":"âm sắc","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"access_token","label":"mã thông báo truy cập","type":"string"}]', 13, 1, NOW(), 1, NOW()),
('SYSTEM_TTS_gizwits', 'TTS', 'gizwits', 'Đám mây trí tuệTTS', '[{"key":"api_url","label":"APIđịa chỉ","type":"string"},{"key":"authorization","label":"Ủy quyền","type":"string"},{"key":"voice","label":"âm sắc","type":"string"},{"key":"output_dir","label":"Thư mục đầu ra","type":"string"},{"key":"access_token","label":"mã thông báo truy cập","type":"string"}]', 14, 1, NOW(), 1, NOW()),

-- Nhà cung cấp mô hình bộ nhớ
('SYSTEM_Memory_mem0ai', 'Memory', 'mem0ai', 'Mem0AIký ức', '[{"key":"api_key","label":"APIchìa khóa","type":"string"}]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_Memory_nomem', 'Memory', 'nomem', 'không có trí nhớ', '[]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_Memory_mem_local_short', 'Memory', 'mem_local_short', 'bộ nhớ ngắn cục bộ', '[]', 3, 1, NOW(), 1, NOW()),

-- Nhà cung cấp mô hình ý định
('SYSTEM_Intent_nointent', 'Intent', 'nointent', 'Không có ý định xác định', '[]', 1, 1, NOW(), 1, NOW()),
('SYSTEM_Intent_intent_llm', 'Intent', 'intent_llm', 'LLMNhận dạng ý định', '[{"key":"llm","label":"LLMngười mẫu","type":"string"}]', 2, 1, NOW(), 1, NOW()),
('SYSTEM_Intent_function_call', 'Intent', 'function_call', 'Nhận dạng ý định cuộc gọi chức năng', '[{"key":"functions","label":"danh sách chức năng","type":"dict","dict_name":"functions"}]', 3, 1, NOW(), 1, NOW());
