# Cài đặt Docker Server

version: '3'
services:
  xiaozhi-esp32-server:
    image: ghcr.nju.edu.cn/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: xiaozhi-esp32-server
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=UTC
    ports:
      # máy chủ ws
      - "8000:8000"
      # cổng dịch vụ http, dùng chophân tích OTA đơn giản (triển khai dịch vụ đơn), vàphân tích phân tích thị giác
      - "8003:8003"
    volumes:
      # thư mục tệp cấu hình
      - ./data:/opt/xiaozhi-esp32-server/data
      # gắn tệp mô hình, rất quan trọng
      - ./models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt